name: Issue Labeler

on:
  issues:
    types: [opened]

permissions:
  issues: write
  
jobs:
  labelIssue:
    runs-on: ubuntu-latest
    steps:
    - name: Add label
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.STACKTIPS_CONTENT_ACTION_TOKEN}}
        script: |
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: ['good first issue', 'triaged']
          })
