name: Issue Labeler

on:
  issues:
    types: [opened, edited]
  
jobs:
  labelIssue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Add label
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: ['good first issue', 'triaged']
          })
